- name: Install ca-certificates
  ansible.builtin.apt:
    name:
      - ca-certificates
    state: present
    update_cache: true

- name: Create keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755' # owner read, write execute, everyone else read + execute

- name: Download Docker GPG Key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0444' # everyone can read

- name: Add Docker APT Repository
  ansible.builtin.apt_repository:
    repo: >
      deb [arch={{ docker_arch }} signed-by=/etc/apt/keyrings/docker.asc]
      https://download.docker.com/linux/ubuntu
      {{ ansible_lsb.codename }} stable
    state: present
    filename: docker

- name: Install Docker + Docker Compose through docker apt repo
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true
